# Generated by Django 5.2.5 on 2025-08-26 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='users/default.png', null=True, upload_to='users/profile_pictures/'),
        ),
    ]
